# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 456)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 431, 431))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.ipName = QtWidgets.QLineEdit(self.tab)
        self.ipName.setGeometry(QtCore.QRect(60, 10, 113, 27))
        self.ipName.setObjectName("ipName")
        self.portName = QtWidgets.QLineEdit(self.tab)
        self.portName.setGeometry(QtCore.QRect(60, 40, 113, 27))
        self.portName.setObjectName("portName")
        self.checkBoxUDP = QtWidgets.QCheckBox(self.tab)
        self.checkBoxUDP.setGeometry(QtCore.QRect(10, 70, 86, 22))
        self.checkBoxUDP.setObjectName("checkBoxUDP")
        self.checkBoxTCP = QtWidgets.QCheckBox(self.tab)
        self.checkBoxTCP.setGeometry(QtCore.QRect(10, 90, 86, 22))
        self.checkBoxTCP.setObjectName("checkBoxTCP")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 55, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 61, 31))
        self.label_6.setObjectName("label_6")
        self.setCfg = QtWidgets.QPushButton(self.tab)
        self.setCfg.setGeometry(QtCore.QRect(150, 240, 171, 27))
        self.setCfg.setObjectName("setCfg")
        self.tabWidget.addTab(self.tab, "")
        self.SenseHatData = QtWidgets.QWidget()
        self.SenseHatData.setObjectName("SenseHatData")
        self.getTemp = QtWidgets.QPushButton(self.SenseHatData)
        self.getTemp.setGeometry(QtCore.QRect(90, 20, 85, 27))
        self.getTemp.setObjectName("getTemp")
        self.label = QtWidgets.QLabel(self.SenseHatData)
        self.label.setGeometry(QtCore.QRect(0, 20, 91, 17))
        self.label.setObjectName("label")
        self.tempNum = QtWidgets.QLCDNumber(self.SenseHatData)
        self.tempNum.setGeometry(QtCore.QRect(320, 20, 71, 23))
        self.tempNum.setObjectName("tempNum")
        self.label_2 = QtWidgets.QLabel(self.SenseHatData)
        self.label_2.setGeometry(QtCore.QRect(260, 20, 55, 17))
        self.label_2.setObjectName("label_2")
        self.getPre = QtWidgets.QPushButton(self.SenseHatData)
        self.getPre.setGeometry(QtCore.QRect(90, 50, 85, 27))
        self.getPre.setObjectName("getPre")
        self.label_3 = QtWidgets.QLabel(self.SenseHatData)
        self.label_3.setGeometry(QtCore.QRect(0, 50, 91, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.SenseHatData)
        self.label_4.setGeometry(QtCore.QRect(260, 50, 55, 17))
        self.label_4.setObjectName("label_4")
        self.preNum = QtWidgets.QLCDNumber(self.SenseHatData)
        self.preNum.setGeometry(QtCore.QRect(320, 50, 71, 23))
        self.preNum.setObjectName("preNum")
        self.tabWidget.addTab(self.SenseHatData, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textToDisplay = QtWidgets.QLineEdit(self.tab_2)
        self.textToDisplay.setGeometry(QtCore.QRect(10, 10, 113, 27))
        self.textToDisplay.setObjectName("textToDisplay")
        self.displayText = QtWidgets.QPushButton(self.tab_2)
        self.displayText.setGeometry(QtCore.QRect(130, 10, 85, 27))
        self.displayText.setObjectName("displayText")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBoxUDP.setText(_translate("MainWindow", "UDP"))
        self.checkBoxTCP.setText(_translate("MainWindow", "TCP"))
        self.label_5.setText(_translate("MainWindow", "IP"))
        self.label_6.setText(_translate("MainWindow", "PORT"))
        self.setCfg.setText(_translate("MainWindow", "Set Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Configuration"))
        self.getTemp.setText(_translate("MainWindow", "Get"))
        self.label.setText(_translate("MainWindow", "Temperature"))
        self.label_2.setText(_translate("MainWindow", "Résulat"))
        self.getPre.setText(_translate("MainWindow", "Get"))
        self.label_3.setText(_translate("MainWindow", "Pressure"))
        self.label_4.setText(_translate("MainWindow", "Résulat"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SenseHatData), _translate("MainWindow", "Sense Hat Data"))
        self.displayText.setText(_translate("MainWindow", "Display Text"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "8x8 Led Data Matrix"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

